# .gitlab-ci.yml

image: mongo:5.0.29-focal

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - apt update
  - apt install -y python3.9
  - python3 --version
  - pip3 install deepdiff
  - pip3 install piper[dev]@git+https://gitlab.com/pipettin-bot/pipettin-piper.git
  - pip3 install .

cache:
  paths:
    - .cache/pip

test:
  stage: test
  script:
    - pytest pylabrobot/resources/pipettin/pipettin_tests.py -k 'not test_with_config_mongo'
    - cat /tmp/piper*.log || echo "No logs found."

# test_with_mongo:
#   stage: test
#   script:
#     - pytest pylabrobot/resources/pipettin/pipettin_tests.py::test_with_config_mongo
#     - cat /tmp/piper*.log || echo "No logs found."
