# .gitlab-ci.yml

image: mongo:5.0.29-focal

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  before_script:
    - apt update && apt install -y python3.9 python3.9-distutils curl git
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.9 get-pip.py
    - pip3.9 install deepdiff
    - pip3.9 install piper[dev]@git+https://gitlab.com/pipettin-bot/pipettin-piper.git
    - pip3.9 install .
    - cp /etc/mongod.conf.orig /etc/mongod.conf
    - mkdir -p /var/lib/mongodb
    - mongod --fork --config /etc/mongod.conf
    - git clone --depth=1 https://gitlab.com/pipettin-bot/pipettin-gui
    - mongoimport --db pipettin --collection platforms --file pipettin-gui/api/src/db/defaults/platforms.json --jsonArray
    - mongoimport --db pipettin --collection protocols --file pipettin-gui/api/src/db/defaults/protocols.json --jsonArray
    - mongoimport --db pipettin --collection workspaces --file pipettin-gui/api/src/db/defaults/workspaces.json --jsonArray
    - mongoimport --db pipettin --collection containers --file pipettin-gui/api/src/db/defaults/containers.json --jsonArray
    - mongoimport --db pipettin --collection settings --file pipettin-gui/api/src/db/defaults/settings.json --jsonArray
    - mongoimport --db pipettin --collection hLprotocols --file pipettin-gui/api/src/db/defaults/hLprotocols.json --jsonArray
    - mongoimport --db pipettin --collection tools --file pipettin-gui/api/src/db/defaults/tools.json --jsonArray
  after_script:
    - pkill mongod

cache:
  paths:
    - .cache/pip

test:
  stage: test
  script:
    - pytest pylabrobot/resources/pipettin/pipettin_tests.py
    - cat /tmp/piper*.log || echo "No logs found."
